### ISSUE TITLE
AND virker ikke i if sætninger

### ISSUE THREAD

**Issue by jwindelborg** [Joklost/P4-Code#18]
OR og NOT virker derimod, rimeligt underligt...

**Comment by jwindelborg** [comment]
![skaermbillede fra 2016-04-20 14-55-03](https://cloud.githubusercontent.com/assets/7478145/14675171/f4395eb4-0707-11e6-8c42-b2e72d928082.png)
Den kode der er kommenteret væk er de sætninger der ikke virker, det som ikke er kommenteret væk compiler fint.

**Comment by jwindelborg** [comment]
Jeg bemærkede at et statment i mit tidligere billede så forkert ud, her er det omskrevet hvor det stadig ikke virker. 
![skaermbillede fra 2016-04-20 14-57-02](https://cloud.githubusercontent.com/assets/7478145/14675217/3dbd179c-0708-11e6-944b-8171185f8e51.png)

 I øvrigt er da og no defineret
![skaermbillede fra 2016-04-20 14-57-50](https://cloud.githubusercontent.com/assets/7478145/14675235/4ee484ce-0708-11e6-8083-9be8dc34e2a3.png)

**Comment by jwindelborg** [comment]
Følgende virker heller ikke 
![skaermbillede fra 2016-04-20 15-03-42](https://cloud.githubusercontent.com/assets/7478145/14675424/36a577b4-0709-11e6-9e2a-b1d8d7ad6526.png)
Mere testing nødvendig for at finde ud af hvad problemet er.

**Comment by jwindelborg** [comment]
Det viser sig at problemet er med flere OR det er ikke et problem at blande bool og int == int

**Comment by pgug** [comment]
`true AND NOT false` er heller ikke gyldig

**Comment by Joklost** [comment]
AND kan bruges i fizzbuzz
![image](https://cloud.githubusercontent.com/assets/9192329/14675896/69f05344-070b-11e6-9a12-d3512e5982a9.png)

**Comment by jwindelborg** [comment]
Dette er mine test cases det føles uforudsigeligt hvad der virker og hvad der ikke gør, andre må gerne teste og forsøge at spore hvornår det virker og hvornår det ikke gør. 
![skaermbillede fra 2016-04-20 15-23-29](https://cloud.githubusercontent.com/assets/7478145/14676018/f9ef6606-070b-11e6-9126-2a8afb2b8f13.png)

**Comment by jwindelborg** [comment]
`If true OR da OR no Then`
Er ikke gyldig kode men
`If (true OR da) OR no Then`
Er gyldig kode
Jeg tænker at der burde være noget der automatisk sætter paranteserne? Måske er alle problemerme med if sætningerne på grund af paranteser?
