### ISSUE TITLE
for loop's skal gentænkes

### ISSUE THREAD

**Issue by jwindelborg** [Joklost/P4-Code#20]
for 1 to 10 ???
for i = 0 to 10 ???
for shit to shit?

Hvad tæller den op, og hvorfor etc?

**Comment by jwindelborg** [comment]
Nuværende adfærd på for loops:

![skaermbillede fra 2016-04-26 11-48-11](https://cloud.githubusercontent.com/assets/7478145/14814036/d5fb4bfa-0ba4-11e6-96a8-644e7156863e.png)
Giver følgende resultat:
![skaermbillede fra 2016-04-26 11-48-37](https://cloud.githubusercontent.com/assets/7478145/14814050/e337cfdc-0ba4-11e6-889e-14262e7f47c5.png)
Det vil sige i bliver ikke talt op.
Et DownTo loop der ser sådan her ud:
![skaermbillede fra 2016-04-26 11-49-31](https://cloud.githubusercontent.com/assets/7478145/14814094/047b8ecc-0ba5-11e6-8172-a41ab34f79a6.png)
Giver ingen output overhovedet

En workaround på for loop for at få i talt med er
![skaermbillede fra 2016-04-26 11-50-31](https://cloud.githubusercontent.com/assets/7478145/14814122/2590a41c-0ba5-11e6-86fd-99e7013e425b.png)
Det giver følgende resultat
![skaermbillede fra 2016-04-26 11-50-52](https://cloud.githubusercontent.com/assets/7478145/14814130/331b6130-0ba5-11e6-9841-f281607a24ec.png)
Hvilket må være nærmere det forventede resultat for første kodestykke hvor i ikke manuelt tælles op. Dog læser jeg `For 1 To 10 Do` som noget der også bør tælle 10 med og ikke stoppe ved 9.

**Comment by jwindelborg** [comment]
Der er problemer med scope i for loops
![skaermbillede fra 2016-04-26 13-39-03](https://cloud.githubusercontent.com/assets/7478145/14816981/52212ff6-0bb4-11e6-919a-10908541c235.png)

Giver følgende fejl
![skaermbillede fra 2016-04-26 13-38-41](https://cloud.githubusercontent.com/assets/7478145/14816975/426766ca-0bb4-11e6-8e18-6da363d00e13.png)
(Bemærk linjenummer passer det er derfor de er inkluderet i billedet)

Det er ikke et generelt problem med while loop er det testet
![skaermbillede fra 2016-04-26 13-40-58](https://cloud.githubusercontent.com/assets/7478145/14817035/97ae31e0-0bb4-11e6-9a01-0ef2d4d192e9.png)
Og det virker perfekt.

**Comment by jwindelborg** [comment]
For loop kan nu nestes fra 177c441

```
Function Void BubbleSort()
      Declare a as Integer[7]
      a[0] = 12
      a[1] = 24
      a[2] = 13
      a[3] = 9
      a[4] = 16
      a[5] = -4
      a[6] = 17
      Declare n as Integer
      n = 7
      Declare i, c, t as Integer
      i = 0
      c = 0
      For i To (n - 1) Do
        For c To (n - i - 1) Do
          If (a[c] > a[c + 1]) Then
            t        = a[c]
            a[c]     = a[c + 1]
            a[c + 1] = t
          End If
        c = c + 1
        End For
      i = i + 1
      End For
End Function
```

Er derfor nu gyldig kode
Før gav det

```
javac com/BattleSim/Declarations.java com/BattleSim/Main.java : stderr: com/BattleSim/Main.java:157: error: variable i795030_forloop is already defined in method BubbleSort()
javac com/BattleSim/Declarations.java com/BattleSim/Main.java : stderr: for (int i795030_forloop=
javac com/BattleSim/Declarations.java com/BattleSim/Main.java : stderr:          ^
javac com/BattleSim/Declarations.java com/BattleSim/Main.java : stderr: 1 error
jar cfm Main.jar Manifest.txt com/BattleSim/Declarations.class com/BattleSim/Main.class : stderr: com/BattleSim/Main.class : no such file or directory
```

**Comment by Monzyy** [comment]
Er løst. For loopet kræver nu en variabel, og inkrementere eller dekrementere variablen alt efter om To eller DownTo er brugt.
