### ISSUE TITLE
Kodegenerering af DclBlock

### ISSUE THREAD

**Issue by Monzyy** [Joklost/P4-Code#21]
Ved at lave en ny node til deklarationer i DclBlock og tilhørende visit metode, kan der generes linjer lignende: "public int i = 0" til Declarations.class . Der vil dermed også kunne udføres assignments og andre statements i Declarations.class filen. Ved at lave alle variabler public kan de tilgås fra Program altså main.  

Følgende er allerede blevet genereret med den eksisterende kode.
![ss 2016-04-21 at 03 11 46](https://cloud.githubusercontent.com/assets/6129407/14709937/9a9977d2-07d3-11e6-968d-5fa5851c8ed3.png)

**Comment by Monzyy** [comment]
Har smidt det jeg har lavet ind til videre på en ny branch og pushet til origin dclBlock

**Comment by Joklost** [comment]
Er ikke sikker på at eksemplet ovenfor virker, da `int i = 0;` kun står inde i constructoren, og stadigt ikke kan tilgås fra Main.

`public class Declarations {`
    `public static int i`
`public Declarations {`
`this.i = 0`
`}`
`}`
Virker muligvis, med en statisk import af klassen.

**Comment by Monzyy** [comment]
Fixed, og der kan nu laves flere .java filer
