### ISSUE TITLE
Funktioner i typer kan ikke tage andre typer som parametre

### ISSUE THREAD

**Issue by Monzyy** [Joklost/P4-Code#34]
Vi har funktionen Teleport i Soldier, som har parameteren **target as Coord**:
![image](https://cloud.githubusercontent.com/assets/6129407/14917950/daaee1c8-0e21-11e6-8554-c0e1a1c42c54.png)
Når Soldier.Teleport kaldes;
![image](https://cloud.githubusercontent.com/assets/6129407/14918045/33c37544-0e22-11e6-98a3-2c10d8f6dd63.png)
For vi fejlen:
![image](https://cloud.githubusercontent.com/assets/6129407/14918068/459cabaa-0e22-11e6-9fb5-5f93d19d360a.png)

**Comment by Monzyy** [comment]
Related to #33 and #32

**Comment by Joklost** [comment]
Se #33 og 3f40fe6233d2049f042f263d3ca74fe96242d4b5
