### ISSUE TITLE
Custom types: Mærkværdig adfærd med assignment

### ISSUE THREAD

**Issue by Monzyy** [Joklost/P4-Code#35]
Vi har typerne:
![image](https://cloud.githubusercontent.com/assets/6129407/14918344/b439d2a8-0e23-11e6-9d55-375f54d9c546.png)
Vi printer target.ToString(), og john.PosToString(), der efter flytter vi john til target (4,5) og printer john.PosToString():
![image](https://cloud.githubusercontent.com/assets/6129407/14918365/cc8a7150-0e23-11e6-8b08-524de904e794.png)
Underligt nok står john på (5,4) i stedet for (4,5):
![image](https://cloud.githubusercontent.com/assets/6129407/14918416/141fddde-0e24-11e6-99fa-34bdfca041df.png)

**Comment by Joklost** [comment]
Kan vidst godt klassificeres som bug.

**Comment by Joklost** [comment]
Se #36
