### ISSUE TITLE
Foretag typechecking

### ISSUE THREAD

**Issue by jwindelborg** [Joklost/P4-Code#4]

**Comment by Joklost** [comment]
@MariusLauge er med

**Comment by Joklost** [comment]
Jeg er ikke helt sikker, men vi kan muligvis godt ende med at få problemer ved funktions kald inde i andre funktioner, eller hvis de ikke allerede er deklarerede inden kaldet..

**Comment by Joklost** [comment]
Nu skal det bare testes, bugs skal findes og smadres og stdlib skal implementeres
