### ISSUE TITLE
Lær java bytecode

### ISSUE THREAD

**Issue by Joklost** [Joklost/P4-Code#6]

**Comment by jwindelborg** [comment]
Can't find mod as an Jasmin instruction. See https://github.com/Joklost/P4-Code/commit/f4ca98ff3f30b28ad922beb01f1e35b8c73e44ae

**Comment by jwindelborg** [comment]
Might have found something in: http://www.student.tugraz.at/elisabeth.getzner/jasmin.pdf testing needed :+1:

**Comment by jwindelborg** [comment]
Worse, how the fuck do I know how big the stack needs to be...
Adding this:

```
ldc "fizz"
Invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
```

Will fuck up the stack, big problem is how is it fixed, `java/io/PrintStream/println(Ljava/lang/String;)V` is loaded at line 37 https://github.com/Joklost/P4-Code/commit/f4ca98ff3f30b28ad922beb01f1e35b8c73e44ae.

Help understanding it will be appriciated.

**Comment by jwindelborg** [comment]
I learn best by working with code, but that's hard without getting code working, so I found more example code, yeah: http://www.cs.sjsu.edu/~pearce/modules/lectures/co/jvm/jasmin/demos/demos.html

EDIT: This is good shit, it is structured fucking good :+1:  :) :100:
